from typing import Any

ALLOW: int
DISALLOW: int
_CALLBACK: int
STDOUTERR: int
ACCESS_EACCES: Any
ACCESS_EAGAIN: Any
ACCESS_EFAULT: Any
ACCESS_EINVAL: Any
ACCESS_ENOENT: Any
ACCESS_EPERM: Any
ACCESS_ENAMETOOLONG: Any
