from typing import List, Dict, Tuple

translator: List[Tuple[List[int], ...]]
by_name: Dict[str, int]
by_id: List[str]
SYSCALL_COUNT: int

sys__sysctl: int
sys_abort2: int
sys_accept: int
sys_accept4: int
sys_access: int
sys_acct: int
sys_acl_aclcheck_fd: int
sys_acl_aclcheck_file: int
sys_acl_aclcheck_link: int
sys_acl_delete_fd: int
sys_acl_delete_file: int
sys_acl_delete_link: int
sys_acl_get_fd: int
sys_acl_get_file: int
sys_acl_get_link: int
sys_acl_set_fd: int
sys_acl_set_file: int
sys_acl_set_link: int
sys_add_key: int
sys_adjtime: int
sys_adjtimex: int
sys_afs3_syscall: int
sys_afs_syscall: int
sys_aio_cancel: int
sys_aio_error: int
sys_aio_fsync: int
sys_aio_mlock: int
sys_aio_read: int
sys_aio_readv: int
sys_aio_return: int
sys_aio_suspend: int
sys_aio_waitcomplete: int
sys_aio_write: int
sys_aio_writev: int
sys_alarm: int
sys_arch_prctl: int
sys_arm_fadvise64_64: int
sys_arm_sync_file_range: int
sys_audit: int
sys_auditctl: int
sys_auditon: int
sys_bdflush: int
sys_bind: int
sys_bindat: int
sys_bpf: int
sys_break: int
sys_brk: int
sys_cachestat: int
sys_cap_enter: int
sys_cap_fcntls_get: int
sys_cap_fcntls_limit: int
sys_cap_get_fd: int
sys_cap_get_file: int
sys_cap_get_proc: int
sys_cap_getmode: int
sys_cap_ioctls_get: int
sys_cap_ioctls_limit: int
sys_cap_new: int
sys_cap_rights_get: int
sys_cap_rights_limit: int
sys_cap_set_fd: int
sys_cap_set_file: int
sys_cap_set_proc: int
sys_capget: int
sys_capset: int
sys_chdir: int
sys_chflags: int
sys_chflagsat: int
sys_chmod: int
sys_chown: int
sys_chown32: int
sys_chroot: int
sys_clock_adjtime: int
sys_clock_adjtime64: int
sys_clock_getcpuclockid2: int
sys_clock_getres: int
sys_clock_getres_time64: int
sys_clock_gettime: int
sys_clock_gettime64: int
sys_clock_nanosleep: int
sys_clock_nanosleep_time64: int
sys_clock_settime: int
sys_clock_settime64: int
sys_clone: int
sys_clone3: int
sys_close: int
sys_close_range: int
sys_closefrom: int
sys_connect: int
sys_connectat: int
sys_copy_file_range: int
sys_cpuset: int
sys_cpuset_getaffinity: int
sys_cpuset_getdomain: int
sys_cpuset_getid: int
sys_cpuset_setaffinity: int
sys_cpuset_setdomain: int
sys_cpuset_setid: int
sys_creat: int
sys_create_module: int
sys_delete_module: int
sys_dup: int
sys_dup2: int
sys_dup3: int
sys_eaccess: int
sys_epoll_create: int
sys_epoll_create1: int
sys_epoll_ctl: int
sys_epoll_ctl_old: int
sys_epoll_pwait: int
sys_epoll_pwait2: int
sys_epoll_wait: int
sys_epoll_wait_old: int
sys_eventfd: int
sys_eventfd2: int
sys_execv: int
sys_execve: int
sys_execveat: int
sys_exit: int
sys_exit_group: int
sys_extattr_delete_fd: int
sys_extattr_delete_file: int
sys_extattr_delete_link: int
sys_extattr_get_fd: int
sys_extattr_get_file: int
sys_extattr_get_link: int
sys_extattr_list_fd: int
sys_extattr_list_file: int
sys_extattr_list_link: int
sys_extattr_set_fd: int
sys_extattr_set_file: int
sys_extattr_set_link: int
sys_extattrctl: int
sys_faccessat: int
sys_faccessat2: int
sys_fadvise64: int
sys_fadvise64_64: int
sys_fallocate: int
sys_fanotify_init: int
sys_fanotify_mark: int
sys_fchdir: int
sys_fchflags: int
sys_fchmod: int
sys_fchmodat: int
sys_fchmodat2: int
sys_fchown: int
sys_fchown32: int
sys_fchownat: int
sys_fchroot: int
sys_fcntl: int
sys_fcntl64: int
sys_fdatasync: int
sys_fexecve: int
sys_ffclock_getcounter: int
sys_ffclock_getestimate: int
sys_ffclock_setestimate: int
sys_fgetxattr: int
sys_fhlink: int
sys_fhlinkat: int
sys_fhopen: int
sys_fhreadlink: int
sys_fhstat: int
sys_fhstatfs: int
sys_finit_module: int
sys_flistxattr: int
sys_flock: int
sys_fork: int
sys_fpathconf: int
sys_fremovexattr: int
sys_fsconfig: int
sys_fsetxattr: int
sys_fsmount: int
sys_fsopen: int
sys_fspacectl: int
sys_fspick: int
sys_fstat: int
sys_fstat64: int
sys_fstatat: int
sys_fstatfs: int
sys_fstatfs64: int
sys_fsync: int
sys_ftime: int
sys_ftruncate: int
sys_ftruncate64: int
sys_funlinkat: int
sys_futex: int
sys_futex_requeue: int
sys_futex_time64: int
sys_futex_wait: int
sys_futex_waitv: int
sys_futex_wake: int
sys_futimens: int
sys_futimes: int
sys_futimesat: int
sys_get_kernel_syms: int
sys_get_mempolicy: int
sys_get_robust_list: int
sys_get_thread_area: int
sys_getaudit: int
sys_getaudit_addr: int
sys_getauid: int
sys_getcontext: int
sys_getcpu: int
sys_getcwd: int
sys_getdents: int
sys_getdents64: int
sys_getdirentries: int
sys_getdomainname: int
sys_getdtablesize: int
sys_getegid: int
sys_getegid32: int
sys_geteuid: int
sys_geteuid32: int
sys_getfh: int
sys_getfhat: int
sys_getfsstat: int
sys_getgid: int
sys_getgid32: int
sys_getgroups: int
sys_getgroups32: int
sys_gethostid: int
sys_gethostname: int
sys_getitimer: int
sys_getkerninfo: int
sys_getlogin: int
sys_getloginclass: int
sys_getpagesize: int
sys_getpeername: int
sys_getpgid: int
sys_getpgrp: int
sys_getpid: int
sys_getpmsg: int
sys_getppid: int
sys_getpriority: int
sys_getrandom: int
sys_getresgid: int
sys_getresgid32: int
sys_getresuid: int
sys_getresuid32: int
sys_getrlimit: int
sys_getrlimitusage: int
sys_getrusage: int
sys_getsid: int
sys_getsockname: int
sys_getsockopt: int
sys_gettid: int
sys_gettimeofday: int
sys_getuid: int
sys_getuid32: int
sys_getxattr: int
sys_getxattrat: int
sys_gssd_syscall: int
sys_gtty: int
sys_idle: int
sys_init_module: int
sys_inotify_add_watch: int
sys_inotify_init: int
sys_inotify_init1: int
sys_inotify_rm_watch: int
sys_io_cancel: int
sys_io_destroy: int
sys_io_getevents: int
sys_io_pgetevents: int
sys_io_pgetevents_time64: int
sys_io_setup: int
sys_io_submit: int
sys_io_uring_enter: int
sys_io_uring_register: int
sys_io_uring_setup: int
sys_ioctl: int
sys_ioperm: int
sys_iopl: int
sys_ioprio_get: int
sys_ioprio_set: int
sys_ipc: int
sys_issetugid: int
sys_jail: int
sys_jail_attach: int
sys_jail_get: int
sys_jail_remove: int
sys_jail_set: int
sys_kcmp: int
sys_kenv: int
sys_kevent: int
sys_kexec_file_load: int
sys_kexec_load: int
sys_keyctl: int
sys_kill: int
sys_killpg: int
sys_kldfind: int
sys_kldfirstmod: int
sys_kldload: int
sys_kldnext: int
sys_kldstat: int
sys_kldsym: int
sys_kldunload: int
sys_kldunloadf: int
sys_kmq_notify: int
sys_kmq_open: int
sys_kmq_setattr: int
sys_kmq_timedreceive: int
sys_kmq_timedsend: int
sys_kmq_unlink: int
sys_kqueue: int
sys_kqueuex: int
sys_kse_create: int
sys_kse_exit: int
sys_kse_release: int
sys_kse_switchin: int
sys_kse_thr_interrupt: int
sys_kse_wakeup: int
sys_ksem_close: int
sys_ksem_destroy: int
sys_ksem_getvalue: int
sys_ksem_init: int
sys_ksem_open: int
sys_ksem_post: int
sys_ksem_timedwait: int
sys_ksem_trywait: int
sys_ksem_unlink: int
sys_ksem_wait: int
sys_ktimer_create: int
sys_ktimer_delete: int
sys_ktimer_getoverrun: int
sys_ktimer_gettime: int
sys_ktimer_settime: int
sys_ktrace: int
sys_landlock_add_rule: int
sys_landlock_create_ruleset: int
sys_landlock_restrict_self: int
sys_lchflags: int
sys_lchmod: int
sys_lchown: int
sys_lchown32: int
sys_lfs_bmapv: int
sys_lfs_markv: int
sys_lfs_segclean: int
sys_lfs_segwait: int
sys_lgetfh: int
sys_lgetxattr: int
sys_link: int
sys_linkat: int
sys_lio_listio: int
sys_listen: int
sys_listmount: int
sys_listxattr: int
sys_listxattrat: int
sys_llistxattr: int
sys_llseek: int
sys_lock: int
sys_lookup_dcookie: int
sys_lpathconf: int
sys_lremovexattr: int
sys_lseek: int
sys_lsetxattr: int
sys_lsm_get_self_attr: int
sys_lsm_list_modules: int
sys_lsm_set_self_attr: int
sys_lstat: int
sys_lstat64: int
sys_lutimes: int
sys_mac_execve: int
sys_mac_get_fd: int
sys_mac_get_file: int
sys_mac_get_link: int
sys_mac_get_pid: int
sys_mac_get_proc: int
sys_mac_set_fd: int
sys_mac_set_file: int
sys_mac_set_link: int
sys_mac_set_proc: int
sys_mac_syscall: int
sys_madvise: int
sys_map_shadow_stack: int
sys_mbind: int
sys_membarrier: int
sys_memfd_create: int
sys_memfd_secret: int
sys_migrate_pages: int
sys_mincore: int
sys_minherit: int
sys_mkdir: int
sys_mkdirat: int
sys_mkfifo: int
sys_mkfifoat: int
sys_mknod: int
sys_mknodat: int
sys_mlock: int
sys_mlock2: int
sys_mlockall: int
sys_mmap: int
sys_mmap2: int
sys_modfind: int
sys_modfnext: int
sys_modify_ldt: int
sys_modnext: int
sys_modstat: int
sys_mount: int
sys_mount_setattr: int
sys_move_mount: int
sys_move_pages: int
sys_mprotect: int
sys_mpx: int
sys_mq_getsetattr: int
sys_mq_notify: int
sys_mq_open: int
sys_mq_timedreceive: int
sys_mq_timedreceive_time64: int
sys_mq_timedsend: int
sys_mq_timedsend_time64: int
sys_mq_unlink: int
sys_mremap: int
sys_mseal: int
sys_msgctl: int
sys_msgget: int
sys_msgrcv: int
sys_msgsnd: int
sys_msgsys: int
sys_msync: int
sys_munlock: int
sys_munlockall: int
sys_munmap: int
sys_name_to_handle_at: int
sys_nanosleep: int
sys_netbsd_lchown: int
sys_netbsd_msync: int
sys_newselect: int
sys_nfsclnt: int
sys_nfsservctl: int
sys_nfssvc: int
sys_nfstat: int
sys_nice: int
sys_nlm_syscall: int
sys_nlstat: int
sys_nmount: int
sys_nnpfs_syscall: int
sys_nstat: int
sys_ntp_adjtime: int
sys_ntp_gettime: int
sys_numa_getaffinity: int
sys_numa_setaffinity: int
sys_oldfstat: int
sys_oldlstat: int
sys_oldolduname: int
sys_oldstat: int
sys_olduname: int
sys_open: int
sys_open_by_handle_at: int
sys_open_tree: int
sys_openat: int
sys_openat2: int
sys_openbsd_poll: int
sys_pathconf: int
sys_pause: int
sys_pciconfig_iobase: int
sys_pciconfig_read: int
sys_pciconfig_write: int
sys_pdfork: int
sys_pdgetpid: int
sys_pdkill: int
sys_perf_event_open: int
sys_personality: int
sys_pidfd_getfd: int
sys_pidfd_open: int
sys_pidfd_send_signal: int
sys_pipe: int
sys_pipe2: int
sys_pivot_root: int
sys_pkey_alloc: int
sys_pkey_free: int
sys_pkey_mprotect: int
sys_poll: int
sys_posix_fadvise: int
sys_posix_fallocate: int
sys_posix_openpt: int
sys_ppoll: int
sys_ppoll_time64: int
sys_prctl: int
sys_pread: int
sys_pread64: int
sys_preadv: int
sys_preadv2: int
sys_prlimit64: int
sys_procctl: int
sys_process_madvise: int
sys_process_mrelease: int
sys_process_vm_readv: int
sys_process_vm_writev: int
sys_prof: int
sys_profil: int
sys_pselect: int
sys_pselect6: int
sys_pselect6_time64: int
sys_ptrace: int
sys_putpmsg: int
sys_pwrite: int
sys_pwrite64: int
sys_pwritev: int
sys_pwritev2: int
sys_query_module: int
sys_quota: int
sys_quotactl: int
sys_quotactl_fd: int
sys_rctl_add_rule: int
sys_rctl_get_limits: int
sys_rctl_get_racct: int
sys_rctl_get_rules: int
sys_rctl_remove_rule: int
sys_read: int
sys_readahead: int
sys_readdir: int
sys_readlink: int
sys_readlinkat: int
sys_readv: int
sys_realpathat: int
sys_reboot: int
sys_recv: int
sys_recvfrom: int
sys_recvmmsg: int
sys_recvmmsg_time64: int
sys_recvmsg: int
sys_remap_file_pages: int
sys_removexattr: int
sys_removexattrat: int
sys_rename: int
sys_renameat: int
sys_renameat2: int
sys_request_key: int
sys_restart_syscall: int
sys_revoke: int
sys_rfork: int
sys_rmdir: int
sys_rpctls_syscall: int
sys_rseq: int
sys_rt_sigaction: int
sys_rt_sigpending: int
sys_rt_sigprocmask: int
sys_rt_sigqueueinfo: int
sys_rt_sigreturn: int
sys_rt_sigsuspend: int
sys_rt_sigtimedwait: int
sys_rt_sigtimedwait_time64: int
sys_rt_tgsigqueueinfo: int
sys_rtprio: int
sys_rtprio_thread: int
sys_sbrk: int
sys_sched_get_priority_max: int
sys_sched_get_priority_min: int
sys_sched_getaffinity: int
sys_sched_getattr: int
sys_sched_getcpu: int
sys_sched_getparam: int
sys_sched_getscheduler: int
sys_sched_rr_get_interval: int
sys_sched_rr_get_interval_time64: int
sys_sched_setaffinity: int
sys_sched_setattr: int
sys_sched_setparam: int
sys_sched_setscheduler: int
sys_sched_yield: int
sys_sctp_generic_recvmsg: int
sys_sctp_generic_sendmsg: int
sys_sctp_generic_sendmsg_iov: int
sys_sctp_peeloff: int
sys_seccomp: int
sys_security: int
sys_select: int
sys_semconfig: int
sys_semctl: int
sys_semget: int
sys_semop: int
sys_semsys: int
sys_semtimedop: int
sys_semtimedop_time64: int
sys_send: int
sys_sendfile: int
sys_sendfile64: int
sys_sendmmsg: int
sys_sendmsg: int
sys_sendto: int
sys_set_mempolicy: int
sys_set_mempolicy_home_node: int
sys_set_robust_list: int
sys_set_thread_area: int
sys_set_tid_address: int
sys_setaudit: int
sys_setaudit_addr: int
sys_setauid: int
sys_setcontext: int
sys_setdomainname: int
sys_setegid: int
sys_seteuid: int
sys_setfib: int
sys_setfsgid: int
sys_setfsgid32: int
sys_setfsuid: int
sys_setfsuid32: int
sys_setgid: int
sys_setgid32: int
sys_setgroups: int
sys_setgroups32: int
sys_sethostid: int
sys_sethostname: int
sys_setitimer: int
sys_setlogin: int
sys_setloginclass: int
sys_setns: int
sys_setpgid: int
sys_setpriority: int
sys_setregid: int
sys_setregid32: int
sys_setresgid: int
sys_setresgid32: int
sys_setresuid: int
sys_setresuid32: int
sys_setreuid: int
sys_setreuid32: int
sys_setrlimit: int
sys_setsid: int
sys_setsockopt: int
sys_settimeofday: int
sys_setugid: int
sys_setuid: int
sys_setuid32: int
sys_setup: int
sys_setxattr: int
sys_setxattrat: int
sys_sgetmask: int
sys_shm_open: int
sys_shm_open2: int
sys_shm_rename: int
sys_shm_unlink: int
sys_shmat: int
sys_shmctl: int
sys_shmdt: int
sys_shmget: int
sys_shmsys: int
sys_shutdown: int
sys_sigaction: int
sys_sigaltstack: int
sys_sigblock: int
sys_sigfastblock: int
sys_siggetmask: int
sys_signal: int
sys_signalfd: int
sys_signalfd4: int
sys_signanosleep: int
sys_sigpending: int
sys_sigprocmask: int
sys_sigqueue: int
sys_sigreturn: int
sys_sigsetmask: int
sys_sigstack: int
sys_sigsuspend: int
sys_sigtimedwait: int
sys_sigvec: int
sys_sigwait: int
sys_sigwaitinfo: int
sys_socket: int
sys_socketcall: int
sys_socketpair: int
sys_specialfd: int
sys_splice: int
sys_ssetmask: int
sys_sstk: int
sys_stat: int
sys_stat64: int
sys_statfs: int
sys_statfs64: int
sys_statmount: int
sys_statx: int
sys_stime: int
sys_stty: int
sys_swapcontext: int
sys_swapoff: int
sys_swapon: int
sys_symlink: int
sys_symlinkat: int
sys_sync: int
sys_sync_file_range: int
sys_syncfs: int
sys_sysarch: int
sys_syscall: int
sys_sysctl: int
sys_sysctlbyname: int
sys_sysfs: int
sys_sysinfo: int
sys_syslog: int
sys_tee: int
sys_tgkill: int
sys_thr_create: int
sys_thr_exit: int
sys_thr_kill: int
sys_thr_kill2: int
sys_thr_new: int
sys_thr_self: int
sys_thr_set_name: int
sys_thr_sleep: int
sys_thr_suspend: int
sys_thr_wake: int
sys_thr_wakeup: int
sys_time: int
sys_timer_create: int
sys_timer_delete: int
sys_timer_getoverrun: int
sys_timer_gettime: int
sys_timer_gettime64: int
sys_timer_settime: int
sys_timer_settime64: int
sys_timerfd_create: int
sys_timerfd_gettime: int
sys_timerfd_gettime64: int
sys_timerfd_settime: int
sys_timerfd_settime64: int
sys_times: int
sys_tkill: int
sys_truncate: int
sys_truncate64: int
sys_tuxcall: int
sys_ugetrlimit: int
sys_ulimit: int
sys_umask: int
sys_umount: int
sys_umount2: int
sys_umtx_lock: int
sys_umtx_op: int
sys_umtx_unlock: int
sys_uname: int
sys_undelete: int
sys_unlink: int
sys_unlinkat: int
sys_unmount: int
sys_unshare: int
sys_uretprobe: int
sys_uselib: int
sys_userfaultfd: int
sys_ustat: int
sys_utime: int
sys_utimensat: int
sys_utimensat_time64: int
sys_utimes: int
sys_utrace: int
sys_uuidgen: int
sys_vadvise: int
sys_vfork: int
sys_vhangup: int
sys_vlimit: int
sys_vm86: int
sys_vm86old: int
sys_vmsplice: int
sys_vread: int
sys_vserver: int
sys_vtimes: int
sys_vtrace: int
sys_vwrite: int
sys_wait: int
sys_wait4: int
sys_wait6: int
sys_waitid: int
sys_waitpid: int
sys_write: int
sys_writev: int
sys_yield: int
