from typing import List, Dict

translator: List[List[int]]
by_name: Dict[str, int]
by_id: List[str]
SYSCALL_COUNT: int

sys__sysctl: int
sys_accept: int
sys_accept4: int
sys_access: int
sys_acct: int
sys_add_key: int
sys_adjtimex: int
sys_afs_syscall: int
sys_alarm: int
sys_arch_prctl: int
sys_arm_fadvise64_64: int
sys_arm_sync_file_range: int
sys_bdflush: int
sys_bind: int
sys_bpf: int
sys_break: int
sys_brk: int
sys_capget: int
sys_capset: int
sys_chdir: int
sys_chmod: int
sys_chown: int
sys_chown32: int
sys_chroot: int
sys_clock_adjtime: int
sys_clock_adjtime64: int
sys_clock_getres: int
sys_clock_getres_time64: int
sys_clock_gettime: int
sys_clock_gettime64: int
sys_clock_nanosleep: int
sys_clock_nanosleep_time64: int
sys_clock_settime: int
sys_clock_settime64: int
sys_clone: int
sys_clone3: int
sys_close: int
sys_close_range: int
sys_connect: int
sys_copy_file_range: int
sys_creat: int
sys_create_module: int
sys_delete_module: int
sys_dup: int
sys_dup2: int
sys_dup3: int
sys_epoll_create: int
sys_epoll_create1: int
sys_epoll_ctl: int
sys_epoll_ctl_old: int
sys_epoll_pwait: int
sys_epoll_pwait2: int
sys_epoll_wait: int
sys_epoll_wait_old: int
sys_eventfd: int
sys_eventfd2: int
sys_execve: int
sys_execveat: int
sys_exit: int
sys_exit_group: int
sys_faccessat: int
sys_faccessat2: int
sys_fadvise64: int
sys_fadvise64_64: int
sys_fallocate: int
sys_fanotify_init: int
sys_fanotify_mark: int
sys_fchdir: int
sys_fchmod: int
sys_fchmodat: int
sys_fchown: int
sys_fchown32: int
sys_fchownat: int
sys_fcntl: int
sys_fcntl64: int
sys_fdatasync: int
sys_fgetxattr: int
sys_finit_module: int
sys_flistxattr: int
sys_flock: int
sys_fork: int
sys_fremovexattr: int
sys_fsconfig: int
sys_fsetxattr: int
sys_fsmount: int
sys_fsopen: int
sys_fspick: int
sys_fstat: int
sys_fstat64: int
sys_fstatat: int
sys_fstatfs: int
sys_fstatfs64: int
sys_fsync: int
sys_ftime: int
sys_ftruncate: int
sys_ftruncate64: int
sys_futex: int
sys_futex_time64: int
sys_futimesat: int
sys_get_kernel_syms: int
sys_get_mempolicy: int
sys_get_robust_list: int
sys_get_thread_area: int
sys_getcpu: int
sys_getcwd: int
sys_getdents: int
sys_getdents64: int
sys_getegid: int
sys_getegid32: int
sys_geteuid: int
sys_geteuid32: int
sys_getgid: int
sys_getgid32: int
sys_getgroups: int
sys_getgroups32: int
sys_getitimer: int
sys_getpeername: int
sys_getpgid: int
sys_getpgrp: int
sys_getpid: int
sys_getpmsg: int
sys_getppid: int
sys_getpriority: int
sys_getrandom: int
sys_getresgid: int
sys_getresgid32: int
sys_getresuid: int
sys_getresuid32: int
sys_getrlimit: int
sys_getrusage: int
sys_getsid: int
sys_getsockname: int
sys_getsockopt: int
sys_gettid: int
sys_gettimeofday: int
sys_getuid: int
sys_getuid32: int
sys_getxattr: int
sys_gtty: int
sys_idle: int
sys_init_module: int
sys_inotify_add_watch: int
sys_inotify_init: int
sys_inotify_init1: int
sys_inotify_rm_watch: int
sys_io_cancel: int
sys_io_destroy: int
sys_io_getevents: int
sys_io_pgetevents: int
sys_io_pgetevents_time64: int
sys_io_setup: int
sys_io_submit: int
sys_io_uring_enter: int
sys_io_uring_register: int
sys_io_uring_setup: int
sys_ioctl: int
sys_ioperm: int
sys_iopl: int
sys_ioprio_get: int
sys_ioprio_set: int
sys_ipc: int
sys_kcmp: int
sys_kexec_file_load: int
sys_kexec_load: int
sys_keyctl: int
sys_kill: int
sys_lchown: int
sys_lchown32: int
sys_lgetxattr: int
sys_link: int
sys_linkat: int
sys_listen: int
sys_listxattr: int
sys_llistxattr: int
sys_llseek: int
sys_lock: int
sys_lookup_dcookie: int
sys_lremovexattr: int
sys_lseek: int
sys_lsetxattr: int
sys_lstat: int
sys_lstat64: int
sys_madvise: int
sys_mbind: int
sys_membarrier: int
sys_memfd_create: int
sys_migrate_pages: int
sys_mincore: int
sys_mkdir: int
sys_mkdirat: int
sys_mknod: int
sys_mknodat: int
sys_mlock: int
sys_mlock2: int
sys_mlockall: int
sys_mmap: int
sys_mmap2: int
sys_modify_ldt: int
sys_mount: int
sys_mount_setattr: int
sys_move_mount: int
sys_move_pages: int
sys_mprotect: int
sys_mpx: int
sys_mq_getsetattr: int
sys_mq_notify: int
sys_mq_open: int
sys_mq_timedreceive: int
sys_mq_timedreceive_time64: int
sys_mq_timedsend: int
sys_mq_timedsend_time64: int
sys_mq_unlink: int
sys_mremap: int
sys_msgctl: int
sys_msgget: int
sys_msgrcv: int
sys_msgsnd: int
sys_msync: int
sys_munlock: int
sys_munlockall: int
sys_munmap: int
sys_name_to_handle_at: int
sys_nanosleep: int
sys_newselect: int
sys_nfsservctl: int
sys_nice: int
sys_oldfstat: int
sys_oldlstat: int
sys_oldolduname: int
sys_oldstat: int
sys_olduname: int
sys_open: int
sys_open_by_handle_at: int
sys_open_tree: int
sys_openat: int
sys_openat2: int
sys_pause: int
sys_pciconfig_iobase: int
sys_pciconfig_read: int
sys_pciconfig_write: int
sys_perf_event_open: int
sys_personality: int
sys_pidfd_getfd: int
sys_pidfd_open: int
sys_pidfd_send_signal: int
sys_pipe: int
sys_pipe2: int
sys_pivot_root: int
sys_pkey_alloc: int
sys_pkey_free: int
sys_pkey_mprotect: int
sys_poll: int
sys_ppoll: int
sys_ppoll_time64: int
sys_prctl: int
sys_pread64: int
sys_preadv: int
sys_preadv2: int
sys_prlimit64: int
sys_process_madvise: int
sys_process_vm_readv: int
sys_process_vm_writev: int
sys_prof: int
sys_profil: int
sys_pselect6: int
sys_pselect6_time64: int
sys_ptrace: int
sys_putpmsg: int
sys_pwrite64: int
sys_pwritev: int
sys_pwritev2: int
sys_query_module: int
sys_quotactl: int
sys_read: int
sys_readahead: int
sys_readdir: int
sys_readlink: int
sys_readlinkat: int
sys_readv: int
sys_reboot: int
sys_recv: int
sys_recvfrom: int
sys_recvmmsg: int
sys_recvmmsg_time64: int
sys_recvmsg: int
sys_remap_file_pages: int
sys_removexattr: int
sys_rename: int
sys_renameat: int
sys_renameat2: int
sys_request_key: int
sys_restart_syscall: int
sys_rmdir: int
sys_rseq: int
sys_rt_sigaction: int
sys_rt_sigpending: int
sys_rt_sigprocmask: int
sys_rt_sigqueueinfo: int
sys_rt_sigreturn: int
sys_rt_sigsuspend: int
sys_rt_sigtimedwait: int
sys_rt_sigtimedwait_time64: int
sys_rt_tgsigqueueinfo: int
sys_sched_get_priority_max: int
sys_sched_get_priority_min: int
sys_sched_getaffinity: int
sys_sched_getattr: int
sys_sched_getparam: int
sys_sched_getscheduler: int
sys_sched_rr_get_interval: int
sys_sched_rr_get_interval_time64: int
sys_sched_setaffinity: int
sys_sched_setattr: int
sys_sched_setparam: int
sys_sched_setscheduler: int
sys_sched_yield: int
sys_seccomp: int
sys_security: int
sys_select: int
sys_semctl: int
sys_semget: int
sys_semop: int
sys_semtimedop: int
sys_semtimedop_time64: int
sys_send: int
sys_sendfile: int
sys_sendfile64: int
sys_sendmmsg: int
sys_sendmsg: int
sys_sendto: int
sys_set_mempolicy: int
sys_set_robust_list: int
sys_set_thread_area: int
sys_set_tid_address: int
sys_setdomainname: int
sys_setfsgid: int
sys_setfsgid32: int
sys_setfsuid: int
sys_setfsuid32: int
sys_setgid: int
sys_setgid32: int
sys_setgroups: int
sys_setgroups32: int
sys_sethostname: int
sys_setitimer: int
sys_setns: int
sys_setpgid: int
sys_setpriority: int
sys_setregid: int
sys_setregid32: int
sys_setresgid: int
sys_setresgid32: int
sys_setresuid: int
sys_setresuid32: int
sys_setreuid: int
sys_setreuid32: int
sys_setrlimit: int
sys_setsid: int
sys_setsockopt: int
sys_settimeofday: int
sys_setuid: int
sys_setuid32: int
sys_setup: int
sys_setxattr: int
sys_sgetmask: int
sys_shmat: int
sys_shmctl: int
sys_shmdt: int
sys_shmget: int
sys_shutdown: int
sys_sigaction: int
sys_sigaltstack: int
sys_siggetmask: int
sys_signal: int
sys_signalfd: int
sys_signalfd4: int
sys_sigpending: int
sys_sigprocmask: int
sys_sigreturn: int
sys_sigsetmask: int
sys_sigsuspend: int
sys_socket: int
sys_socketcall: int
sys_socketpair: int
sys_splice: int
sys_ssetmask: int
sys_stat: int
sys_stat64: int
sys_statfs: int
sys_statfs64: int
sys_statx: int
sys_stime: int
sys_stty: int
sys_swapoff: int
sys_swapon: int
sys_symlink: int
sys_symlinkat: int
sys_sync: int
sys_sync_file_range: int
sys_syncfs: int
sys_syscall: int
sys_sysctl: int
sys_sysfs: int
sys_sysinfo: int
sys_syslog: int
sys_tee: int
sys_tgkill: int
sys_time: int
sys_timer_create: int
sys_timer_delete: int
sys_timer_getoverrun: int
sys_timer_gettime: int
sys_timer_gettime64: int
sys_timer_settime: int
sys_timer_settime64: int
sys_timerfd_create: int
sys_timerfd_gettime: int
sys_timerfd_gettime64: int
sys_timerfd_settime: int
sys_timerfd_settime64: int
sys_times: int
sys_tkill: int
sys_truncate: int
sys_truncate64: int
sys_tuxcall: int
sys_ugetrlimit: int
sys_ulimit: int
sys_umask: int
sys_umount: int
sys_umount2: int
sys_uname: int
sys_unlink: int
sys_unlinkat: int
sys_unshare: int
sys_uselib: int
sys_userfaultfd: int
sys_ustat: int
sys_utime: int
sys_utimensat: int
sys_utimensat_time64: int
sys_utimes: int
sys_vfork: int
sys_vhangup: int
sys_vm86: int
sys_vm86old: int
sys_vmsplice: int
sys_vserver: int
sys_wait4: int
sys_waitid: int
sys_waitpid: int
sys_write: int
sys_writev: int
