from typing import Any

sys__sysctl: Any
sys_accept: Any
sys_accept4: Any
sys_access: Any
sys_acct: Any
sys_add_key: Any
sys_adjtimex: Any
sys_afs_syscall: Any
sys_alarm: Any
sys_arch_prctl: Any
sys_arm_fadvise64_64: Any
sys_arm_sync_file_range: Any
sys_bdflush: Any
sys_bind: Any
sys_bpf: Any
sys_break: Any
sys_brk: Any
sys_capget: Any
sys_capset: Any
sys_chdir: Any
sys_chmod: Any
sys_chown: Any
sys_chown32: Any
sys_chroot: Any
sys_clock_adjtime: Any
sys_clock_adjtime64: Any
sys_clock_getres: Any
sys_clock_getres_time64: Any
sys_clock_gettime: Any
sys_clock_gettime64: Any
sys_clock_nanosleep: Any
sys_clock_nanosleep_time64: Any
sys_clock_settime: Any
sys_clock_settime64: Any
sys_clone: Any
sys_clone3: Any
sys_close: Any
sys_connect: Any
sys_copy_file_range: Any
sys_creat: Any
sys_create_module: Any
sys_delete_module: Any
sys_dup: Any
sys_dup2: Any
sys_dup3: Any
sys_epoll_create: Any
sys_epoll_create1: Any
sys_epoll_ctl: Any
sys_epoll_ctl_old: Any
sys_epoll_pwait: Any
sys_epoll_wait: Any
sys_epoll_wait_old: Any
sys_eventfd: Any
sys_eventfd2: Any
sys_execve: Any
sys_execveat: Any
sys_exit: Any
sys_exit_group: Any
sys_faccessat: Any
sys_fadvise64: Any
sys_fadvise64_64: Any
sys_fallocate: Any
sys_fanotify_init: Any
sys_fanotify_mark: Any
sys_fchdir: Any
sys_fchmod: Any
sys_fchmodat: Any
sys_fchown: Any
sys_fchown32: Any
sys_fchownat: Any
sys_fcntl: Any
sys_fcntl64: Any
sys_fdatasync: Any
sys_fgetxattr: Any
sys_finit_module: Any
sys_flistxattr: Any
sys_flock: Any
sys_fork: Any
sys_fremovexattr: Any
sys_fsconfig: Any
sys_fsetxattr: Any
sys_fsmount: Any
sys_fsopen: Any
sys_fspick: Any
sys_fstat: Any
sys_fstat64: Any
sys_fstatat: Any
sys_fstatfs: Any
sys_fstatfs64: Any
sys_fsync: Any
sys_ftime: Any
sys_ftruncate: Any
sys_ftruncate64: Any
sys_futex: Any
sys_futex_time64: Any
sys_futimesat: Any
sys_get_kernel_syms: Any
sys_get_mempolicy: Any
sys_get_robust_list: Any
sys_get_thread_area: Any
sys_getcpu: Any
sys_getcwd: Any
sys_getdents: Any
sys_getdents64: Any
sys_getegid: Any
sys_getegid32: Any
sys_geteuid: Any
sys_geteuid32: Any
sys_getgid: Any
sys_getgid32: Any
sys_getgroups: Any
sys_getgroups32: Any
sys_getitimer: Any
sys_getpeername: Any
sys_getpgid: Any
sys_getpgrp: Any
sys_getpid: Any
sys_getpmsg: Any
sys_getppid: Any
sys_getpriority: Any
sys_getrandom: Any
sys_getresgid: Any
sys_getresgid32: Any
sys_getresuid: Any
sys_getresuid32: Any
sys_getrlimit: Any
sys_getrusage: Any
sys_getsid: Any
sys_getsockname: Any
sys_getsockopt: Any
sys_gettid: Any
sys_gettimeofday: Any
sys_getuid: Any
sys_getuid32: Any
sys_getxattr: Any
sys_gtty: Any
sys_idle: Any
sys_init_module: Any
sys_inotify_add_watch: Any
sys_inotify_init: Any
sys_inotify_init1: Any
sys_inotify_rm_watch: Any
sys_io_cancel: Any
sys_io_destroy: Any
sys_io_getevents: Any
sys_io_pgetevents: Any
sys_io_pgetevents_time64: Any
sys_io_setup: Any
sys_io_submit: Any
sys_io_uring_enter: Any
sys_io_uring_register: Any
sys_io_uring_setup: Any
sys_ioctl: Any
sys_ioperm: Any
sys_iopl: Any
sys_ioprio_get: Any
sys_ioprio_set: Any
sys_ipc: Any
sys_kcmp: Any
sys_kexec_file_load: Any
sys_kexec_load: Any
sys_keyctl: Any
sys_kill: Any
sys_lchown: Any
sys_lchown32: Any
sys_lgetxattr: Any
sys_link: Any
sys_linkat: Any
sys_listen: Any
sys_listxattr: Any
sys_llistxattr: Any
sys_llseek: Any
sys_lock: Any
sys_lookup_dcookie: Any
sys_lremovexattr: Any
sys_lseek: Any
sys_lsetxattr: Any
sys_lstat: Any
sys_lstat64: Any
sys_madvise: Any
sys_mbind: Any
sys_membarrier: Any
sys_memfd_create: Any
sys_migrate_pages: Any
sys_mincore: Any
sys_mkdir: Any
sys_mkdirat: Any
sys_mknod: Any
sys_mknodat: Any
sys_mlock: Any
sys_mlock2: Any
sys_mlockall: Any
sys_mmap: Any
sys_mmap2: Any
sys_modify_ldt: Any
sys_mount: Any
sys_move_mount: Any
sys_move_pages: Any
sys_mprotect: Any
sys_mpx: Any
sys_mq_getsetattr: Any
sys_mq_notify: Any
sys_mq_open: Any
sys_mq_timedreceive: Any
sys_mq_timedreceive_time64: Any
sys_mq_timedsend: Any
sys_mq_timedsend_time64: Any
sys_mq_unlink: Any
sys_mremap: Any
sys_msgctl: Any
sys_msgget: Any
sys_msgrcv: Any
sys_msgsnd: Any
sys_msync: Any
sys_munlock: Any
sys_munlockall: Any
sys_munmap: Any
sys_name_to_handle_at: Any
sys_nanosleep: Any
sys_newselect: Any
sys_nfsservctl: Any
sys_nice: Any
sys_oldfstat: Any
sys_oldlstat: Any
sys_oldolduname: Any
sys_oldstat: Any
sys_olduname: Any
sys_open: Any
sys_open_by_handle_at: Any
sys_open_tree: Any
sys_openat: Any
sys_openat2: Any
sys_pause: Any
sys_pciconfig_iobase: Any
sys_pciconfig_read: Any
sys_pciconfig_write: Any
sys_perf_event_open: Any
sys_personality: Any
sys_pidfd_getfd: Any
sys_pidfd_open: Any
sys_pidfd_send_signal: Any
sys_pipe: Any
sys_pipe2: Any
sys_pivot_root: Any
sys_pkey_alloc: Any
sys_pkey_free: Any
sys_pkey_mprotect: Any
sys_poll: Any
sys_ppoll: Any
sys_ppoll_time64: Any
sys_prctl: Any
sys_pread64: Any
sys_preadv: Any
sys_preadv2: Any
sys_prlimit64: Any
sys_process_vm_readv: Any
sys_process_vm_writev: Any
sys_prof: Any
sys_profil: Any
sys_pselect6: Any
sys_pselect6_time64: Any
sys_ptrace: Any
sys_putpmsg: Any
sys_pwrite64: Any
sys_pwritev: Any
sys_pwritev2: Any
sys_query_module: Any
sys_quotactl: Any
sys_read: Any
sys_readahead: Any
sys_readdir: Any
sys_readlink: Any
sys_readlinkat: Any
sys_readv: Any
sys_reboot: Any
sys_recv: Any
sys_recvfrom: Any
sys_recvmmsg: Any
sys_recvmmsg_time64: Any
sys_recvmsg: Any
sys_remap_file_pages: Any
sys_removexattr: Any
sys_rename: Any
sys_renameat: Any
sys_renameat2: Any
sys_request_key: Any
sys_restart_syscall: Any
sys_rmdir: Any
sys_rseq: Any
sys_rt_sigaction: Any
sys_rt_sigpending: Any
sys_rt_sigprocmask: Any
sys_rt_sigqueueinfo: Any
sys_rt_sigreturn: Any
sys_rt_sigsuspend: Any
sys_rt_sigtimedwait: Any
sys_rt_sigtimedwait_time64: Any
sys_rt_tgsigqueueinfo: Any
sys_sched_get_priority_max: Any
sys_sched_get_priority_min: Any
sys_sched_getaffinity: Any
sys_sched_getattr: Any
sys_sched_getparam: Any
sys_sched_getscheduler: Any
sys_sched_rr_get_interval: Any
sys_sched_rr_get_interval_time64: Any
sys_sched_setaffinity: Any
sys_sched_setattr: Any
sys_sched_setparam: Any
sys_sched_setscheduler: Any
sys_sched_yield: Any
sys_seccomp: Any
sys_security: Any
sys_select: Any
sys_semctl: Any
sys_semget: Any
sys_semop: Any
sys_semtimedop: Any
sys_semtimedop_time64: Any
sys_send: Any
sys_sendfile: Any
sys_sendfile64: Any
sys_sendmmsg: Any
sys_sendmsg: Any
sys_sendto: Any
sys_set_mempolicy: Any
sys_set_robust_list: Any
sys_set_thread_area: Any
sys_set_tid_address: Any
sys_setdomainname: Any
sys_setfsgid: Any
sys_setfsgid32: Any
sys_setfsuid: Any
sys_setfsuid32: Any
sys_setgid: Any
sys_setgid32: Any
sys_setgroups: Any
sys_setgroups32: Any
sys_sethostname: Any
sys_setitimer: Any
sys_setns: Any
sys_setpgid: Any
sys_setpriority: Any
sys_setregid: Any
sys_setregid32: Any
sys_setresgid: Any
sys_setresgid32: Any
sys_setresuid: Any
sys_setresuid32: Any
sys_setreuid: Any
sys_setreuid32: Any
sys_setrlimit: Any
sys_setsid: Any
sys_setsockopt: Any
sys_settimeofday: Any
sys_setuid: Any
sys_setuid32: Any
sys_setup: Any
sys_setxattr: Any
sys_sgetmask: Any
sys_shmat: Any
sys_shmctl: Any
sys_shmdt: Any
sys_shmget: Any
sys_shutdown: Any
sys_sigaction: Any
sys_sigaltstack: Any
sys_siggetmask: Any
sys_signal: Any
sys_signalfd: Any
sys_signalfd4: Any
sys_sigpending: Any
sys_sigprocmask: Any
sys_sigreturn: Any
sys_sigsetmask: Any
sys_sigsuspend: Any
sys_socket: Any
sys_socketcall: Any
sys_socketpair: Any
sys_splice: Any
sys_ssetmask: Any
sys_stat: Any
sys_stat64: Any
sys_statfs: Any
sys_statfs64: Any
sys_statx: Any
sys_stime: Any
sys_stty: Any
sys_swapoff: Any
sys_swapon: Any
sys_symlink: Any
sys_symlinkat: Any
sys_sync: Any
sys_sync_file_range: Any
sys_syncfs: Any
sys_syscall: Any
sys_sysctl: Any
sys_sysfs: Any
sys_sysinfo: Any
sys_syslog: Any
sys_tee: Any
sys_tgkill: Any
sys_time: Any
sys_timer_create: Any
sys_timer_delete: Any
sys_timer_getoverrun: Any
sys_timer_gettime: Any
sys_timer_gettime64: Any
sys_timer_settime: Any
sys_timer_settime64: Any
sys_timerfd_create: Any
sys_timerfd_gettime: Any
sys_timerfd_gettime64: Any
sys_timerfd_settime: Any
sys_timerfd_settime64: Any
sys_times: Any
sys_tkill: Any
sys_truncate: Any
sys_truncate64: Any
sys_tuxcall: Any
sys_ugetrlimit: Any
sys_ulimit: Any
sys_umask: Any
sys_umount: Any
sys_umount2: Any
sys_uname: Any
sys_unlink: Any
sys_unlinkat: Any
sys_unshare: Any
sys_uselib: Any
sys_userfaultfd: Any
sys_ustat: Any
sys_utime: Any
sys_utimensat: Any
sys_utimensat_time64: Any
sys_utimes: Any
sys_vfork: Any
sys_vhangup: Any
sys_vm86: Any
sys_vm86old: Any
sys_vmsplice: Any
sys_vserver: Any
sys_wait4: Any
sys_waitid: Any
sys_waitpid: Any
sys_write: Any
sys_writev: Any
