name: mypy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies and mypy
      run: |
        pip install cython mypy
        pip install -r requirements.txt
    - name: Verify mypy types
      run: |
        mypy --version
        mypy .
